# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password')

# Recipe Categories
Category.create!(category:"Cakes")
Category.create!(category:"Confections")
Category.create!(category:"Cookies")
Category.create!(category:"Custards")
Category.create!(category:"Frozen")
Category.create!(category:"Garnishes")
Category.create!(category:"Sauces")

# Ingredients
Ingredient.create!(ingredient:"granulated sugar")
Ingredient.create!(ingredient:"powdered sugar")
Ingredient.create!(ingredient:"trimoline")
Ingredient.create!(ingredient:"glucose syrup")
Ingredient.create!(ingredient:"glucose powder")
Ingredient.create!(ingredient:"egg, whole")
Ingredient.create!(ingredient:"egg white")
Ingredient.create!(ingredient:"egg yolk")
Ingredient.create!(ingredient:"milk")
Ingredient.create!(ingredient:"heavy cream")
Ingredient.create!(ingredient:"butter")
Ingredient.create!(ingredient:"nonfat milk powder")
Ingredient.create!(ingredient:"sweetened condensed milk")
Ingredient.create!(ingredient:"all-purpose flour")
Ingredient.create!(ingredient:"cake flour")
Ingredient.create!(ingredient:"almond paste")
Ingredient.create!(ingredient:"praline paste")
Ingredient.create!(ingredient:"peanut butter")
Ingredient.create!(ingredient:"sliced almonds")
Ingredient.create!(ingredient:"lemon juice")
Ingredient.create!(ingredient:"lemons, zest only")
Ingredient.create!(ingredient:"lychee puree")
Ingredient.create!(ingredient:"mango puree")
Ingredient.create!(ingredient:"white chocolate couverture")
Ingredient.create!(ingredient:"milk chocolate couverture")
Ingredient.create!(ingredient:"dark chocolate couverture")
Ingredient.create!(ingredient:"cocoa powder")
Ingredient.create!(ingredient:"vanilla bean powder")
Ingredient.create!(ingredient:"matcha")
Ingredient.create!(ingredient:"Vietnamese cinnamon powder")
Ingredient.create!(ingredient:"water")
Ingredient.create!(ingredient:"gelatin sheet")
Ingredient.create!(ingredient:"agar powder")
Ingredient.create!(ingredient:"ice cream stabilizer")
Ingredient.create!(ingredient:"sorbet stabilizer")
Ingredient.create!(ingredient:"baking soda")
Ingredient.create!(ingredient:"baking powder")
Ingredient.create!(ingredient:"salt")
Ingredient.create!(ingredient:"pastry cream")